name 'smarmie-networker'
version '0.1.0'
author 'smarmie (andrei.staicu@gmail.com)'
license 'GPL 2.0'
summary 'Networker module'
description 'Networker module'
source 'git://github.com/smarmie/networker.git'
project_page 'http://github.com/smarmie/networker'
dependency 'puppetlabs/stdlib', '4.1.0'
